name: DevSecOps Pipeline with SAST and DAST

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sast:
    name: Static Code Analysis (Semgrep)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Semgrep
        run: |
          curl -s https://semgrep.dev/install.sh | bash

      - name: Run Semgrep Scan
        run: semgrep --config=auto --json > semgrep_results.json

      - name: Upload Semgrep Report
        uses: actions/upload-artifact@v2
        with:
          name: semgrep-report
          path: semgrep_results.json

  dast:
    name: Dynamic App Security Testing (OWASP ZAP)
    runs-on: ubuntu-latest
    needs: sast  # DAST runs after SAST
    steps:
      - name: Pull DVWA Docker Image
        run: docker pull vulnerables/web-dvwa

      - name: Run DVWA Container
        run: docker run -d -p 8080:80 --name dvwa vulnerables/web-dvwa

      - name: Wait for DVWA to start
        run: sleep 30

      - name: Run OWASP ZAP Scan
        run: |
          docker pull owasp/zap2docker-stable
          docker run --network host owasp/zap2docker-stable zap-baseline.py \
            -t http://localhost:8080 -r zap_report.html

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v2
        with:
          name: zap-report
          path: zap_report.html
