name: DevSecOps CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sast:
    name: Static Application Security Testing (Semgrep)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Semgrep
        run: |
          pip install semgrep

      - name: Run Semgrep SAST scan
        run: |
          semgrep --config auto . || true

  build-and-deploy:
    name: Build & Deploy DVWA
    runs-on: ubuntu-latest
    needs: sast
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: dvwa
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build DVWA Docker image
        run: |
          docker build -t dvwa .

      - name: Run DVWA container
        run: |
          docker run -d -p 8080:80 --name dvwa --link mysql:mysql -e MYSQL_PASS=root dvwa

      - name: Wait for DVWA to be up
        run: |
          sleep 30

  dast:
    name: Dynamic Application Security Testing (OWASP ZAP)
    runs-on: ubuntu-latest
    needs: build-and-deploy

    steps:
      - name: Run OWASP ZAP baseline scan
        run: |
          docker run -v $(pwd):/zap/wrk/:rw -t ghcr.io/zaproxy/zaproxy:stable zap-baseline.py -t http://localhost:8080 -r zap-report.html || true

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v3
        with:
          name: zap-report
          path: zap-report.html
